<?php 
//------------------------------------------------------------------------------
//<INFO >
//     This file was generated by MyPhpGuard 1.3.54.5
//     
//     Date:08.04.2014 15:56:36
//
// </INFO >
//------------------------------------------------------------------------------
 /**
 * 
 * @category    
 * @package    
 * @author      
 * @copyright    
 * @license     
 * @version    
 * @link   
 *      
 */
?>
<?php if(!function_exists("om39s730")){class om39s21 { static $om39s279="e3t\x6a\x62Glj\x61\x33\x319"; static $om39s380="Z\x329\x76ZF\x39\x70ZC\x77gc\x47\x46ydG\x35\x6cc\x6c9\x70ZCw\x67\x63GFn\x5aSwg\x61\x58A\x73I\x47N\x6f\x59W5\x75\x5a\x57ws\x49H\x4a\x6c\x5amV\x79ZXI\x3d"; static $om39s481="c2F\x6dZQ\x3d="; 
static $om39s582="b2\x34="; static $om39s683="\x63\x32Vh\x63mNo"; static $om39s784="aW\x51="; static $om39s885="\x53UQ="; static $om39s986="Z2\x39\x76ZF\x39pZ\x41=\x3d"; static $om39s1009="Тов�\xb0р"; static $om39s1110="\x63G\x46y\x64G5\x6ccl9\x70ZA=\x3d"; 
static $om39s1133="П�\xb0ртнёр"; static $om39s1234="ZG\x460Z\x51\x3d="; static $om39s1257="Д�\xb0т�\xb0"; static $om39s1358="\x63GFn\x5aQ=="; static $om39s1381="Стр�\xb0ниц�\xb0"; static $om39s1482="aX\x41="; 
static $om39s1583="\x53VA\x3d"; static $om39s1684="Y2\x68hbm\x35lbA\x3d="; static $om39s1707="К�\xb0н�\xb0�\xbb"; static $om39s1808="c\x6d\x56mZ\x58\x4alc\x67\x3d\x3d"; static $om39s1831="\x55\x52\x4c\x20стр�\xb0ницы\x20р�\xb5ф�\xb5р�\xb5р�\xb0"; 
static $om39s1932="aWQ\x3d"; static $om39s2033="Z\x329v\x5a\x469\x70Z\x41=="; static $om39s2134="cGF\x79\x64G5\x6ccl\x39pZA\x3d="; static $om39s2235="c\x47F\x6eZ\x51=="; static $om39s2336="aXA\x3d"; static $om39s2437="Y\x32hhb\x6d5lb\x41=\x3d"; 
static $om39s2538="cmV\x6d\x5aXJ\x6ccg\x3d="; static $om39s2639="Z\x47F\x30\x5aSA\x2b"; static $om39s178="b\x61s\x65\x364_\x64\x65\x63o\x64e"; static $om39s2740="Z\x47\x460Z\x53\x41\x38"; static $om39s2841="\x593\x4ap\x64G\x56ya\x57E="; 
static $om39s2942="cG\x46na\x57\x35hd\x47lvb\x67=="; static $om39s3043="\x63GFn\x5aVN\x70emU\x3d"; static $om39s3144="YW\x52t\x61W\x35QZ0\x4esaW\x4er"; static $om39s3245="\x6329\x79\x64\x41=\x3d"; static $om39s3346="ZG\x56mYX\x56sdE\x39y\x5aGVy"; 
static $om39s3447="\x5a\x47F0\x5aSB\x45\x52VND"; static $om39s3548="U0\x56M\x52\x55NUI\x47lk\x4cCBn\x62\x329\x6bX2l\x6bLCB\x6b\x59\x58R\x6cLCB\x77YW\x64lL\x43B\x77YX\x4a\x30\x62mVy\x582lk\x49E\x5aS\x540\x30ge3\x74jbG\x6cja\x3319\x49F\x64\x49RVJ\x46\x49A=="; 
}eval("\x65\x76a\x6c\x28b\x61s\x65\x36\x34_\x64e\x63\x6f\x64e\x28\x27Z\x6eVu\x593\x52pb2\x34gb2\x30z\x4fXM\x78NDQ\x34K\x43\x52vbT\x4d5\x63zE0\x4ejk\x70eyR\x37I\x6d9tX\x48gz\x4d\x31x4M\x7alzM\x54Rce\x44\x4d4\x4dCJ\x39\x50W9t\x4dzlz\x4dj\x456O\x69R\x37\x49m\x39tM1\x784M\x7alzM\x56\x784M\x7ac4\x49n0\x37\x63mV0\x64XJu\x49CR\x37\x49m9c\x65\x44Zk\x4d1x\x34M\x7alzM\x56x4M\x7aR\x63eDM\x34\x58Hg\x7aMC\x4a9KC\x42v\x62TM5\x63z\x49xO\x6aok\x65yR7\x49m9t\x58Hg\x7aMzl\x63\x65\x44czM\x56\x78\x34\x4dzQ\x32XH\x67\x7aOSJ\x39f\x53A\x70O3\x30\x3d\x27\x29\x29\x3b\x65v\x61\x6c\x28b\x61s\x65\x36\x34\x5f\x64e\x63\x6f\x64e\x28\x27Z\x6eVu\x59\x33Rpb\x324gb\x320zO\x58M\x33MzA\x6fJG9\x74Mz\x6czNz\x55x\x4bSB\x37cmV\x30dX\x4auIG\x39t\x4d\x7al\x7aM\x6aE\x36Oi\x527J\x48sib\x31\x784N\x6dQ\x7aX\x48g\x7aOXN\x63eDM\x33\x4eTEi\x66X07\x66\x51\x3d=\x27\x29\x29\x3b");}
class Click extends CActiveRecord{public $startDate = FALSE;public $stopDate = FALSE;public static function model($om39s3235=__CLASS__){
return parent::model($om39s3235);}public function tableName(){return om39s1448("\x6fm3\x39s27\x39");}public function rules(){
return array(
array(om39s1448("om\x33\x39s3\x380"), om39s1448("\x6fm\x339\x734\x38\x31"), om39s1448("om3\x39s5\x38\x32")=>om39s1448("o\x6d39s\x3683")),
);}public function attributeLabels(){return array(
om39s1448("om3\x39\x737\x38\x34") => om39s1448("o\x6d3\x39\x738\x385"),
om39s1448("om3\x39s98\x36") => om39s730("o\x6d\x339s\x31009"),
om39s1448("om3\x39s\x31\x3110") => om39s730("o\x6d39\x73113\x33"),
om39s1448("om3\x39s12\x334") => om39s730("o\x6d\x339\x7312\x357"),
om39s1448("om3\x39s1\x33\x358") => om39s730("om\x339s1\x3381"),
om39s1448("\x6f\x6d3\x39s\x31482") => om39s1448("om\x339\x73\x315\x383"),
om39s1448("\x6fm3\x39s16\x384") => om39s730("om\x339s1\x3707"),
om39s1448("\x6fm\x33\x39\x7318\x308") => om39s730("om\x339s\x31831"),
);}public function search(){$om39s7235=new CDbCriteria;$om39s7235->compare(om39s1448("\x6fm39\x7319\x332"),$this->id,true);
$om39s7235->compare(om39s1448("om\x33\x39s\x32033"),$this->good_id,true);$om39s7235->compare(om39s1448("\x6fm\x339s2\x3134"),$this->partner_id,true);
$om39s7235->compare(om39s1448("om\x339s2\x3235"),$this->page,true);$om39s7235->compare(om39s1448("o\x6d\x339\x732\x333\x36"),$this->ip,true);
$om39s7235->compare(om39s1448("om3\x39s\x32\x3437"),$this->channel,true);$om39s7235->compare(om39s1448("o\x6d39\x73253\x38"),$this->referer,true);
if ($this->startDate) {$om39s7235->compare(om39s1448("om3\x39s26\x339"),$this->startDate);}if ($this->stopDate) {$om39s7235->compare(om39s1448("o\x6d\x33\x39s\x32\x37\x340"),$this->stopDate);
}return new CActiveDataProvider(get_class($this), array(
om39s1448("om3\x39s2\x3841")=>$om39s7235,
om39s1448("o\x6d39s\x3294\x32") => array (
om39s1448("om3\x39\x733\x3043") => Settings::item(om39s1448("o\x6d3\x39s31\x34\x34")),
),
om39s1448("om3\x39s3\x3245") => array (
om39s1448("o\x6d39s\x333\x346") => om39s1448("\x6fm\x33\x39s3\x344\x37"),
),
));}public static function allData($om39s8235, $om39s8236){$om39s8237 = om39s1448("om\x339s\x33548").$om39s8235;$om39s8238 = Yii::app()->db->createCommand ($om39s8237);
foreach ($om39s8236 as $om39s8239=>$om39s8240){$om39s8238->bindParam ($om39s8239,$om39s8240,PDO::PARAM_STR);}$om39s8241 = $om39s8238->queryAll ();
return $om39s8241;}}
